name: Trigger auto deployment for aaaaa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ janewby/WebChat ]
    paths:
    - '**'
    - '.github/workflows/aaaaa-AutoDeployTrigger-2793cae0-310f-4e7d-9742-ea9248ad9db0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AAAAA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AAAAA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AAAAA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: meomeoqt2i3x6qzjideregistry.azurecr.io
          registryUsername: ${{ secrets.AAAAA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AAAAA_REGISTRY_PASSWORD }}
          containerAppName: aaaaa
          resourceGroup: chat-app-rg
          imageToBuild: meomeoqt2i3x6qzjideregistry.azurecr.io/aaaaa:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


